%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_SequenceProxyPushSupplier
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_opu_o.2015-03-31_14/otp_src_17/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPUSHSUPPLIER_HRL).
-define(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPUSHSUPPLIER_HRL, true).




-endif.


