%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventDomainAdmin_EventDomain
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_opu_o.2015-03-31_14/otp_src_17/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTDOMAINADMIN_EVENTDOMAIN_HRL).
-define(COSEVENTDOMAINADMIN_EVENTDOMAIN_HRL, true).




-endif.


