%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_SubtransactionsUnavailable
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_opu_o.2015-03-31_14/otp_src_17/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_SubtransactionsUnavailable').
-ic_compiled("4_3_6").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/SubtransactionsUnavailable:1.0",
                   "SubtransactionsUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/SubtransactionsUnavailable:1.0".

%% returns name
name() -> "CosTransactions_SubtransactionsUnavailable".



