%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_opu_o.2015-03-31_14/otp_src_17/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_HRL).
-define(COSEVENTCHANNELADMIN_HRL, true).


-record('CosEventChannelAdmin_AlreadyConnected', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0"}).
-record('CosEventChannelAdmin_TypeError', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/TypeError:1.0"}).


-endif.


